//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zapis_na_kryzhok.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int lessonID { get; set; }
        public int teacherID { get; set; }
        public int tariffID { get; set; }
        public System.DateTime date { get; set; }
        public string classroomNumber { get; set; }
    
        public virtual Tariffs Tariffs { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
