//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zapis_na_kryzhok.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signs
    {
        public int signID { get; set; }
        public int personID { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual Persons Persons { get; set; }
    }
}
